package hello.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/create-order") // This means URL's start with /orders (after Application path)
public class CreatOrderController {
	@Autowired // This means to get the bean called orderRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private hello.OrderRepository orderRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewOrder (@RequestParam String fromAddr, @RequestParam String toAddr, 
			@RequestParam String until, @RequestParam String timeframe, @RequestParam String typeOfAnimal, 
			@RequestParam Integer numberOfAnimals, @RequestParam String timeEstimation, @RequestParam String startTime, 
			@RequestParam String driver) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		

		hello.AniOrder n = new hello.AniOrder();
		n.setFromAddr(fromAddr);
		n.setToAddr(toAddr);
		n.setUntil(until);;
		n.setTimeframe(timeframe);
		n.setTypeOfAnimal(typeOfAnimal);
		n.setNumberOfAnimals(numberOfAnimals);
		n.setTimeEstimation(timeEstimation);
		n.setStartTime(startTime);
		n.setDriver(driver);
		orderRepository.save(n);
		return "add-order-success";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<hello.AniOrder> getAllOrders() {
		// This returns a JSON or XML with the users
		return orderRepository.findAll();
	}


}